### ISSUE TITLE
how do you make it an exe it just says it's a spec file help please?

### ISSUE THREAD

**Issue by MidnightApora** [independent-coder/Roblox-Webhooks#2]

**Comment by independent-coder** [comment]
Did you try the manual version or use the [RCG-EXE-Builder](https://github.com/independent-coder/Roblox-Webhooks/blob/main/RCG-EXE-Builder.exe)? If you're using the RCG EXE BUILDER, it needs to have a spec file; it's only a log file, and you're supposed to have an executable (exe) file. If you're using the manual method with auto-py-to-exe, the executable app should be in 'C:\Users\USERNAME\output\R0blUx-Gr@bber.exe.' I apologize for the delayed response. I hope this fixes your problem, and if there are any new issues, I'd love to help fix them. Ciao!

**Comment by ghost** [comment]
i dont have an exe tho
